language: python

python:

  - '3.6.7'

# safelist

branches:

  only:

    - dev


before_script:

  - pipenv install


env: DJANGO_SETTINGS_MODULE="myfirstband.travis_settings"

services:

  - postgresql

addons:
  postgresql: "9.5"

script:

  - python manage.py test