# Generated by Django 2.1.5 on 2019-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='level',
            field=models.CharField(blank=True, max_length=80, verbose_name='niveau de maitrise'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Genre'),
        ),
    ]
