# Generated by Django 2.1.5 on 2019-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0007_auto_20190114_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument',
            field=models.CharField(choices=[('Accordéoniste', 'Accordéoniste'), ('Bassiste', 'Bassiste'), ('Batteur', 'Batteur'), ('Cuivriste', 'Cuivriste'), ('Clarinetiste', 'Clarinetiste'), ('Clavieriste', 'Clavieriste'), ('Contrebassiste', 'Contrebassiste'), ('Flutiste', 'Flutiste'), ('Guitariste', 'Guitariste'), ('Harmoniciste', 'Harmoniciste'), ('Percussionniste', 'Percussionniste'), ('Pianiste', 'Pianiste'), ('Saxophoniste', 'Saxophoniste'), ('Violoniste', 'Violoniste')], max_length=80, verbose_name='instrument'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='level',
            field=models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Confirmé', 'Confirmé'), ('Professionnel', 'Professionnel')], max_length=80, verbose_name='niveau de maitrise'),
        ),
    ]
