# Generated by Django 2.1.5 on 2019-01-18 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0008_auto_20190115_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1918), django.core.validators.MaxValueValidator(2019)], verbose_name='Année de naissance'),
        ),
    ]
