# Generated by Django 2.1.5 on 2019-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0009_auto_20190118_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='Nom'),
        ),
    ]
