# Generated by Django 2.1.5 on 2019-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0010_auto_20190205_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=60, verbose_name='Nom'),
        ),
    ]
