# Generated by Django 2.1.5 on 2019-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0012_auto_20190214_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Nom'),
        ),
    ]
