# Generated by Django 2.1.5 on 2019-02-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0013_auto_20190214_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument',
            field=models.CharField(choices=[('Accordéoniste', 'Accordéoniste'), ('Bassiste', 'Bassiste'), ('Batteur', 'Batteur'), ('Chanteur', 'Chanteur(se)'), ('Cuivriste', 'Cuivriste'), ('Clarinetiste', 'Clarinetiste'), ('Clavieriste', 'Clavieriste'), ('Contrebassiste', 'Contrebassiste'), ('Flutiste', 'Flutiste'), ('Guitariste', 'Guitariste'), ('Harmoniciste', 'Harmoniciste'), ('Percussionniste', 'Percussionniste'), ('Pianiste', 'Pianiste'), ('Saxophoniste', 'Saxophoniste'), ('Violoniste', 'Violoniste')], max_length=80, verbose_name='instrument'),
        ),
    ]
