# Generated by Django 2.1.5 on 2019-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0017_auto_20190221_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='Nom'),
        ),
    ]
