# Generated by Django 2.1.7 on 2019-03-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0020_auto_20190318_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nom'),
        ),
    ]
