# Generated by Django 2.1.5 on 2019-02-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name="Titre de l'annonce")),
                ('content', models.TextField(max_length=500, verbose_name="Texte de l'annonce")),
                ('county_name', models.CharField(blank=True, max_length=60, verbose_name='Nom du département')),
                ('town', models.CharField(blank=True, max_length=60, verbose_name='Ville')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicianAnswerAnnonucement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, verbose_name='Reponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('musician_announcement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.MusicianAnnouncement')),
            ],
        ),
    ]
