# Generated by Django 2.1.5 on 2019-02-21 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_auto_20190219_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicianAnswerAnnonucement',
            new_name='MusicianAnswerAnnouncement',
        ),
        migrations.RenameField(
            model_name='musiciananswerannouncement',
            old_name='musician_announcement_id',
            new_name='musician_announcement',
        ),
    ]
