# Generated by Django 2.1.7 on 2019-02-27 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0003_auto_20190221_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiciananswerannouncement',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musiciananswerannouncement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musiciananswerannouncement',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='announcement.MusicianAnswerAnnouncement'),
        ),
    ]
