# Generated by Django 2.1.7 on 2019-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20190227_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianannouncement',
            name='code',
            field=models.CharField(blank=True, max_length=5, verbose_name='code postal'),
        ),
    ]
