# Generated by Django 2.1.5 on 2019-01-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='En cours de création', max_length=80, unique=True, verbose_name='Nom du Groupe')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Courte description')),
                ('code', models.CharField(blank=True, max_length=5, verbose_name='code postal')),
                ('county_name', models.CharField(blank=True, max_length=60, verbose_name='Nom du département')),
                ('town', models.CharField(blank=True, max_length=60, verbose_name='Ville')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='band_avatar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Groupe de Compos', 'Groupe de Compos'), ('Groupe de Reprises', 'Groupe de Reprises')], max_length=80, verbose_name='Type')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.Band')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicalGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musical_genre', models.CharField(choices=[('Blues', 'Blues'), ('Chorale', 'Chorale'), ('Electro', 'Electro'), ('Folk', 'Folk'), ('Funk', 'Funk'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Musique du Monde', 'Musique du Monde'), ('Pop', 'Pop'), ('Punk', 'Punk'), ('Rap', 'Rap'), ('Reggae', 'Reggae'), ("Rock 'n' roll", "Rock 'n' roll"), ('Ska', 'Ska'), ('Soul', 'Soul'), ('Variété', 'Variété')], max_length=80, verbose_name='Genre musical')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='band.Band')),
            ],
        ),
    ]
