# Generated by Django 2.1.5 on 2019-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='type',
            field=models.CharField(choices=[('Groupe de Compos', 'Groupe de Compos'), ('Groupe de Reprises', 'Groupe de Reprises')], max_length=80, verbose_name='Type'),
        ),
    ]
