# Generated by Django 2.1.5 on 2019-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_auto_20190131_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='type',
            field=models.CharField(blank=True, choices=[('Groupe de Compos', 'Groupe de Compos'), ('Groupe de Reprises', 'Groupe de Reprises')], max_length=80, null=True, verbose_name='Type'),
        ),
    ]
