# Generated by Django 2.1.5 on 2019-01-29 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0002_auto_20190128_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='UserBand',
        ),
    ]
