# Generated by Django 2.1.5 on 2019-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20190129_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalgenre',
            name='band',
        ),
        migrations.AddField(
            model_name='band',
            name='musical_genre',
            field=models.CharField(choices=[('Blues', 'Blues'), ('Chorale', 'Chorale'), ('Electro', 'Electro'), ('Folk', 'Folk'), ('Funk', 'Funk'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Musique du Monde', 'Musique du Monde'), ('Pop', 'Pop'), ('Punk', 'Punk'), ('Rap', 'Rap'), ('Reggae', 'Reggae'), ("Rock 'n' roll", "Rock 'n' roll"), ('Ska', 'Ska'), ('Soul', 'Soul'), ('Variété', 'Variété')], max_length=80, null=True, verbose_name='Genre musical'),
        ),
        migrations.AlterField(
            model_name='band',
            name='type',
            field=models.CharField(choices=[('Groupe de Compos', 'Groupe de Compos'), ('Groupe de Reprises', 'Groupe de Reprises')], max_length=80, null=True, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='MusicalGenre',
        ),
    ]
