# Generated by Django 2.1.5 on 2019-02-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20190131_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description du groupe'),
        ),
        migrations.AlterField(
            model_name='band',
            name='type',
            field=models.CharField(blank=True, choices=[('Groupe de Compos', 'Groupe de Compos'), ('Groupe de Reprises', 'Groupe de Reprises')], max_length=80, null=True, verbose_name='Type de groupe'),
        ),
    ]
