# Generated by Django 2.1.5 on 2019-02-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20190201_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(default='nom-du-groupe', max_length=150),
            preserve_default=False,
        ),
    ]
