# Generated by Django 2.1.5 on 2019-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_band_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
