# Generated by Django 2.1.5 on 2019-02-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('band', '0007_auto_20190204_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='band',
            name='musical_genre',
            field=models.CharField(blank=True, choices=[('Blues', 'Blues'), ('Chorale', 'Chorale'), ('Electro', 'Electro'), ('Folk', 'Folk'), ('Funk', 'Funk'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Musique du Monde', 'Musique du Monde'), ('Pop', 'Pop'), ('Punk', 'Punk'), ('Rap', 'Rap'), ('Reggae', 'Reggae'), ("Rock 'n' roll", "Rock 'n' roll"), ('Ska', 'Ska'), ('Soul', 'Soul'), ('Variété', 'Variété')], max_length=80, null=True, verbose_name='Genre musical'),
        ),
    ]
